### ISSUE TITLE
Periodic version of sparse_distance_matrix

### ISSUE THREAD

**Issue by gabrielelanaro** [patvarilly/periodic_kdtree#1]
It would be very useful to me to have a periodic implementation of sparse_distance_matrix for ckdtree. Do you think is it hard to implement?

Do you have any suggestion on how to proceed?

**Comment by patvarilly** [comment]
Dear Gabriele,

It shouldn't be too hard, but I will be travelling during the weekend. If you're willing to experiment, I've also coded up cover trees (on my github page as well) with an interface nearly identical to ckdtree. A cover tree is a generalization of a kd-tree to any metric function, not just Euclidean distances. This includes periodic distances.  Unfortunately, cover trees are a bit slower, and at least my code is not cythonized.

Best of luck!

Patrick

-------- Original Message --------
Subject: [periodic_kdtree] Periodic version of sparse_distance_matrix (#1)

**Comment by gabrielelanaro** [comment]
Thank you! I guess that in my case it would be better to move to cover-trees. The periodicity seems more natural with them.
